name: Release
on:
  push:
    branches:
      - 'master'
  workflow_run:
    workflows:
      - ""
    branches:
      - "master"
    types:
      - "completed"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: |
            [
              {
                "id": "github",
                "username": "${env.USER}",
                "password": "${env.PASS}"
              }
            ]
          repositories: |
            [
              {
                "id": "central",
                "url": "https://repo.maven.apache.org/maven2",
                "snapshots": {
                  "enabled": "false"
                }
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/tnweiss/benchmarkr-java",
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
      - name: Build with maven
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
